### PR TITLE
Rescue using full capacity of USB drive + sync.

### PR DESCRIPTION
**Pull request by PeterFalken**
Daniil,
This is a small update to the ermk-reinstall script that asks the user if they want to use the full capacity of the USB drive. If the user answers no - then the previous default values are used.

Added a sync command at the request of forums users.

### CODE REVIEW

**Comment by shaneog** [comment]
Bump. This would be great to have!

**Comment by dmbaturin** [comment]
Thanks! Sorry it took so long. I've been out of the EdgeOS world for quite a while (roughly since the time UBNT dropped any open source pretense...), and to be fair I don't have that cross-compile setup handy anymore so I'd need to redo it if I were to make a new version. This thing essentially needs a new maintainer.

**Comment by PeterFalken** [comment]
I'm sure there are more than one person (including me, that could server as maintainers). In the end this is a community effort. Just point us to the instructions of how to build the cross-compile environment. By the way - I've also seen a few other solutions out there that restore the USB on an external system - using these scripts as reference.

**Comment by dmbaturin** [comment]
Yeah, it seems for ERL specifically, most people are now using external scripts. I suppose the main direction for the EMRK 2.0 should be support for hardware that has its flash drive soldered to the board, though that one is also that most problematic for two reasons.
Obviously once bricked, that hardware cannot be restored until EMRK works with it, which is why I never got to it when I was still an active EdgeOS community member, ER8 was my main router and I couldn't risk losing it potentially for weeks; but there's more to it. ERL and ER8 use a different hardware platform, and Cavium didn't release a complete SDK for it. What complicates it is that my long time friends and collegues from Vyatta who used to work on EdgeOS quit UBNT a while ago so I don't have anyone to ask about the inner workings of the newer hardware.

Still, I do have an ER8 that is now unused, so I can participate in the effort. Here's the brain dump:

ERL and ER8 use Cavium Octeon CPUs. I have no idea about ERX, it may be different. The Octeon SDK comes in two varieties: one is only available for their partners and includes full documentation and source code of the acceleration drivers to be compiled against their supported kernel (which is why EdgeOS is using old kernels patched to death). The other only includes a supported GCC, kernel source, some rudimentary documentation and code examples and is theoretically available to everyone.

The free SDK can be downloaded from http://cnusers.org , but I say theoretically because you need an account to download it, accounts are manually approved and it took me a month or two go get mine. The GPL parts are definitely legal to redistribute though so if you have a similar problem registering, I can fetch them for you, I've checked that my account still works.

For the ERL, you need to use SDK 2.0. It includes precompiled GCC so it's comparatively easy to use. I wrote build instructions on the UBNT forum back then: https://community.ubnt.com/t5/EdgeMAX/Kernel-rebuild-step-by-step/m-p/523707/highlight/true#M12582
I suppose it may be better to use a recent Debian, and EdgeOS itself is now wheezy-based. However, check if newer ERLs use different kernel version,  maybe it needs a newer SDK as well.

ER8 uses a different platform that needs SDK 3.0. At the time it was not available in a pre-compiled form, maybe now it is, I'd need to check. If nothing else compiling the kernel for the least common denominator MIPS64 may work. I've never built a kernel for ER8 myself.

The binaries I used in the initrd from EMRK come directly from then-current EdgeOS, I suppose newer versions can as well do the same.

**Comment by UBNT-cmb** [comment]
@dmbaturin is there reference somewhere to what you did to create that .bin file after compiling things? I can do the compilation easily, but not sure how to create the .bin from there. 

Incidentally happened upon this today, after I bricked some USG3s doing development and was hoping not to disassemble them to re-flash. The board type for USG3 (essentially same hardware as ERL) isn't in the current .bin so it doesn't work, but should be easy to add. 

I don't think it'd be hard to extend support to all the other Cavium platforms (all of them except ER-X which is Mediatek). Worst case I can re-flash them the same way they're loaded in the factory, so I at least have a semi-easy way to recover if it goes awry. I won't be able to spend a ton of time on it, and it'd probably have to be a weekend project, but I'm willing to give it a shot.

**Pull request merged**
